//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HashLibEntities : DbContext
    {
        public HashLibEntities()
            : base("name=HashLibEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gg_Download_Record> gg_download_record { get; set; }
        public DbSet<Gg_Login_Record> gg_login_record { get; set; }
        public DbSet<Gg_Register_Message> gg_register_message { get; set; }
        public DbSet<Gg_Share_Record> gg_share_record { get; set; }
        public DbSet<Hash_Arithmetic> hash_arithmetic { get; set; }
        public DbSet<Hash_Dbversion> hash_dbversion { get; set; }
        public DbSet<Hash_File_Info_Upload_Statistics> hash_file_info_upload_statistics { get; set; }
        public DbSet<Hash_File_Property> hash_file_property { get; set; }
        public DbSet<Hash_Hit_Info> hash_hit_info { get; set; }
        public DbSet<Hash_Hit_Services_Statistics> hash_hit_services_statistics { get; set; }
        public DbSet<Hash_Install_Info> hash_install_info { get; set; }
        public DbSet<Hash_Rule_Config> hash_rule_config { get; set; }
        public DbSet<Sys_Area> sys_area { get; set; }
        public DbSet<Sys_Config> sys_config { get; set; }
        public DbSet<Sys_Department> sys_department { get; set; }
        public DbSet<Sys_Department_Character_Code> sys_department_character_code { get; set; }
        public DbSet<Sys_Dictionary> sys_dictionary { get; set; }
        public DbSet<Sys_Log> sys_log { get; set; }
        public DbSet<Sys_Menu> sys_menu { get; set; }
        public DbSet<Sys_Role> sys_role { get; set; }
        public DbSet<Sys_Role_Right> sys_role_right { get; set; }
        public DbSet<Sys_User> sys_user { get; set; }
        public DbSet<Sys_User_Role> sys_user_role { get; set; }
        public DbSet<Sys_Button> sys_button { get; set; }
        public DbSet<Hash_Hit_Statistics> Hash_Hit_Statistics { get; set; }
        public DbSet<Hash_Collect_Set_Statistics> Hash_Collect_Set_Statistics { get; set; }
        public DbSet<Hash_File_Info_Audit> Hash_File_Info_Audit { get; set; }
        public DbSet<Hash_Property_Update_Statistics> Hash_Property_Update_Statistics { get; set; }
        public DbSet<Hash_Down_Dbrecord> Hash_Down_Dbrecord { get; set; }
        public DbSet<Hash_File_Upload_Info> Hash_File_Upload_Info { get; set; }
        public DbSet<Hash_Collect_Statistics> Hash_Collect_Statistics { get; set; }
        public DbSet<Hash_File_Info> Hash_File_Info { get; set; }
        public DbSet<Hash_Collect_Set> Hash_Collect_Set { get; set; }
        public DbSet<Hash_Collect_Record> Hash_Collect_Record { get; set; }
        public DbSet<Hash_File_Confirm_Statistics> Hash_File_Confirm_Statistics { get; set; }
        public DbSet<Sys_Soft> Sys_Soft { get; set; }
        public DbSet<Sys_Fault> Sys_Fault { get; set; }
        public DbSet<Hash_Collect_Statistics_Details> Hash_Collect_Statistics_Details { get; set; }
        public DbSet<Hash_Collectfile_Upload_Info> Hash_Collectfile_Upload_Info { get; set; }
    }
}
