//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gg_Download_Record : BaseModel
    {
    	[EntityPrimKey]
        public string Download_Record_ID { get; set; }
        public Nullable<int> Download_Type { get; set; }
        public string File_Name { get; set; }
        public string MD5 { get; set; }
        public string Other_Hash { get; set; }
        public Nullable<System.DateTime> Download_Time { get; set; }
        public string Source_IP { get; set; }
        public Nullable<int> Source_Port { get; set; }
        public string Destination_IP { get; set; }
        public Nullable<int> Destination_Port { get; set; }
        public string IMEI { get; set; }
        public string Remark { get; set; }
    
        public virtual Gg_Register_Message Gg_Register_Message { get; set; }
    }
}
