//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Type_Info : BaseModel
    {
        public Hash_Type_Info()
        {
            this.hash_hit_statistics = new HashSet<Hash_Hit_Statistics>();
            this.hash_file_info = new HashSet<Hash_File_Info>();
        }
    
    	[EntityPrimKey]
        public string Type_ID { get; set; }
        public string Type_Name { get; set; }
        public string Remark { get; set; }
    
        public virtual Hash_Folder Hash_Folder { get; set; }
        public virtual ICollection<Hash_Hit_Statistics> hash_hit_statistics { get; set; }
        public virtual ICollection<Hash_File_Info> hash_file_info { get; set; }
    }
}
