//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Folder : BaseModel
    {
        public Hash_Folder()
        {
            this.Hash_Type_Info = new HashSet<Hash_Type_Info>();
        }
    
    	[EntityPrimKey]
        public string Folder_ID { get; set; }
        public string Folder_Name { get; set; }
        public Nullable<int> Int_Folder_ID { get; set; }
        public string Paths { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Hash_Type_Info> Hash_Type_Info { get; set; }
    }
}
