//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Install_Info : BaseModel
    {
    	[EntityPrimKey]
        public string Install_ID { get; set; }
        public string Name { get; set; }
        public string Package_Name { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<System.DateTime> Install_Time { get; set; }
        public string Path { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Hash_Collect_Record hash_collect_record { get; set; }
    }
}
