//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Collect_Set_Statistics : BaseModel
    {
    	[EntityPrimKey]
        public string Collect_Set_Statistics_ID { get; set; }
        public string Collect_Type { get; set; }
        public Nullable<System.DateTime> Collect_Time { get; set; }
        public Nullable<int> Collect_Set_Amount { get; set; }
        public Nullable<int> Collect_Amount { get; set; }
        public Nullable<int> Source_Amount { get; set; }
        public Nullable<int> Hit_Amount { get; set; }
    
        public virtual Sys_Department Sys_Department { get; set; }
    }
}
