//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_File_Confirm_Statistics : BaseModel
    {
    	[EntityPrimKey]
        public string File_Confirm_Statistics_ID { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> FirstConfirm_Amount { get; set; }
        public Nullable<System.DateTime> LastUpdateFirstConfirmAmount_Time { get; set; }
        public Nullable<int> FinalConfirm_Amount { get; set; }
        public Nullable<System.DateTime> LastUpdateFinalConfirmAmount_Time { get; set; }
        public string Department_Paths { get; set; }
        public string Area_Paths { get; set; }
    
        public virtual Sys_Department sys_department { get; set; }
        public virtual Sys_User sys_user { get; set; }
        public virtual Sys_Area sys_area { get; set; }
    }
}
