//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Collect_Record : BaseModel
    {
        public Hash_Collect_Record()
        {
            this.hash_hit_info = new HashSet<Hash_Hit_Info>();
            this.hash_install_info = new HashSet<Hash_Install_Info>();
        }
    
    	[EntityPrimKey]
        public string Collect_Record_ID { get; set; }
        public Nullable<System.DateTime> Collect_Time { get; set; }
        public Nullable<System.DateTime> Upload_Time { get; set; }
        public string Source_Owner { get; set; }
        public string Collect_Set_Type { get; set; }
        public string Collect_Set_Key { get; set; }
        public string Source_Owner_Pcs { get; set; }
        public string Source_Owner_Minzu { get; set; }
        public string Source_Type { get; set; }
        public string Source_Mark { get; set; }
        public string Source_IDCard { get; set; }
        public Nullable<int> Source_IDCard_Type { get; set; }
        public Nullable<int> Collect_Time_Span { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Avail_Count { get; set; }
        public Nullable<int> Total_Count { get; set; }
        public string DB_Version { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string ExceptionIDCardNO { get; set; }
        public string FloderName { get; set; }
    
        public virtual Sys_User sys_user { get; set; }
        public virtual Hash_Collect_Set hash_collect_set { get; set; }
        public virtual ICollection<Hash_Hit_Info> hash_hit_info { get; set; }
        public virtual ICollection<Hash_Install_Info> hash_install_info { get; set; }
    }
}
