//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Hit_Services_Statistics : BaseModel
    {
    	[EntityPrimKey]
        public string Hit_Services_Statistics_ID { get; set; }
        public string Department_ID { get; set; }
        public Nullable<System.DateTime> Collect_Time { get; set; }
        public Nullable<int> Levels_First_Amount { get; set; }
        public Nullable<int> Levels_Second_Amount { get; set; }
        public Nullable<int> Levels_Third_Amount { get; set; }
        public Nullable<int> Levels_Forth_Amount { get; set; }
    }
}
