//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Rule_Config : BaseModel
    {
        public Hash_Rule_Config()
        {
            this.Hash_Arithmetic = new HashSet<Hash_Arithmetic>();
            this.Hash_Dbversion = new HashSet<Hash_Dbversion>();
        }
    
    	[EntityPrimKey]
        public string Rule_ID { get; set; }
        public string Rule_Name { get; set; }
        public Nullable<int> Rule_Type { get; set; }
        public string Use_Interface { get; set; }
        public string Group_Code { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
    
        public virtual ICollection<Hash_Arithmetic> Hash_Arithmetic { get; set; }
        public virtual ICollection<Hash_Dbversion> Hash_Dbversion { get; set; }
    }
}
