//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_File_Upload_Info : BaseModel
    {
        public Hash_File_Upload_Info()
        {
            this.hash_file_info = new HashSet<Hash_File_Info>();
        }
    
    	[EntityPrimKey]
        public string File_Upload_Info_ID { get; set; }
        public Nullable<int> Source_Type { get; set; }
        public string Source_Name { get; set; }
        public string Site_Url { get; set; }
        public string Equipement_Type { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Host_Name { get; set; }
        public string IP { get; set; }
        public string Mac_Address { get; set; }
        public Nullable<System.DateTime> Local_Uplaod_Time { get; set; }
    
        public virtual ICollection<Hash_File_Info> hash_file_info { get; set; }
    }
}
