//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_File_Info_Audit : BaseModel
    {
    	[EntityPrimKey]
        public string Audit_ID { get; set; }
        public string Opinion { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
    
        public virtual Sys_User sys_user { get; set; }
        public virtual Hash_File_Info hash_file_info { get; set; }
    }
}
