//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Collect_Set : BaseModel
    {
        public Hash_Collect_Set()
        {
            this.hash_collect_record = new HashSet<Hash_Collect_Record>();
        }
    
    	[EntityPrimKey]
        public string Collect_Set_ID { get; set; }
        public string Collect_Set_Type { get; set; }
        public string Collect_Set_Key { get; set; }
        public string DB_Version { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string App_Version { get; set; }
        public string Department_Paths { get; set; }
    
        public virtual Sys_Department sys_department { get; set; }
        public virtual ICollection<Hash_Collect_Record> hash_collect_record { get; set; }
    }
}
