//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Down_Dbrecord : BaseModel
    {
    	[EntityPrimKey]
        public string DownRecord_ID { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Remark { get; set; }
    
        public virtual Hash_Dbversion Hash_Dbversion { get; set; }
        public virtual Sys_User Sys_User { get; set; }
    }
}
