//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Dbversion : BaseModel
    {
        public Hash_Dbversion()
        {
            this.hash_down_dbrecord = new HashSet<Hash_Down_Dbrecord>();
        }
    
    	[EntityPrimKey]
        public string DbVersion_ID { get; set; }
        public string Version { get; set; }
        public string Types { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Paths { get; set; }
        public string Remark { get; set; }
        public long File_Count { get; set; }
    
        public virtual Hash_Rule_Config Hash_Rule_Config { get; set; }
        public virtual ICollection<Hash_Down_Dbrecord> hash_down_dbrecord { get; set; }
    }
}
