//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Arithmetic : BaseModel
    {
    	[EntityPrimKey]
        public string Arithmetic_ID { get; set; }
        public string Arithmetic_Value { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
    
        public virtual Hash_Rule_Config Hash_Rule_Config { get; set; }
        public virtual Hash_File_Info hash_file_info { get; set; }
    }
}
