//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Property_Update_Statistics : BaseModel
    {
    	[EntityPrimKey]
        public string Property_Update_Statistics_ID { get; set; }
        public Nullable<int> Collect_Set_Amount { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string DBVersion { get; set; }
        public Nullable<int> Update_Amount { get; set; }
        public Nullable<int> UnUpdate_Amount { get; set; }
        public Nullable<int> Download_Amount { get; set; }
        public Nullable<System.DateTime> LastUpdateCollectSetAmount_Time { get; set; }
        public Nullable<System.DateTime> LastUpdateUpdateAmount_Time { get; set; }
        public Nullable<System.DateTime> LastUpdateUnupdateAmount_Time { get; set; }
        public Nullable<System.DateTime> LastUpdateDownloadAmount_Time { get; set; }
        public string Department_Paths { get; set; }
        public string Area_Paths { get; set; }
    
        public virtual Sys_Department Sys_Department { get; set; }
        public virtual Sys_Area sys_area { get; set; }
    }
}
