//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash_Collect_Statistics_Details : BaseModel
    {
    	[EntityPrimKey]
        public string Collect_Statistics_Details_ID { get; set; }
        public string Public_Name { get; set; }
        public string FileType_Name { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Hash_Collect_Statistics hash_collect_statistics { get; set; }
    }
}
