//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Soft : BaseModel
    {
    	[EntityPrimKey]
        public string Soft_ID { get; set; }
        public string Soft_Name { get; set; }
        public string Soft_Model { get; set; }
        public bool Is_Show { get; set; }
        public string Remark { get; set; }
        public int Download_Count { get; set; }
        public System.DateTime Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Soft_Image { get; set; }
        public string Soft_Version { get; set; }
        public string Soft_Path { get; set; }
    }
}
