//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log : BaseModel
    {
    	[EntityPrimKey]
        public string Log_ID { get; set; }
        public Nullable<System.DateTime> Operate_Time { get; set; }
        public Nullable<int> Operate_Type { get; set; }
        public string Operate_Url { get; set; }
        public string Operate_Content { get; set; }
        public string Operate_IP { get; set; }
        public string Module_Name { get; set; }
    
        public virtual Sys_User Sys_User { get; set; }
    }
}
