//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User : BaseModel
    {
        public Sys_User()
        {
            this.Sys_Log = new HashSet<Sys_Log>();
            this.Sys_User_Role = new HashSet<Sys_User_Role>();
            this.hash_down_dbrecord = new HashSet<Hash_Down_Dbrecord>();
            this.hash_file_info_audit = new HashSet<Hash_File_Info_Audit>();
            this.hash_file_info = new HashSet<Hash_File_Info>();
            this.hash_collect_record = new HashSet<Hash_Collect_Record>();
            this.hash_file_confirm_statistics = new HashSet<Hash_File_Confirm_Statistics>();
        }
    
    	[EntityPrimKey]
        public string User_ID { get; set; }
        public string Account { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string IDCard { get; set; }
        public Nullable<int> Status { get; set; }
        public string Police_Code { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public string Last_Login_IP { get; set; }
        public Nullable<System.DateTime> Last_Login_Time { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Creator_ID { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Updater_ID { get; set; }
        public string Remark { get; set; }
    
        public virtual Sys_Department Sys_Department { get; set; }
        public virtual ICollection<Sys_Log> Sys_Log { get; set; }
        public virtual ICollection<Sys_User_Role> Sys_User_Role { get; set; }
        public virtual ICollection<Hash_Down_Dbrecord> hash_down_dbrecord { get; set; }
        public virtual ICollection<Hash_File_Info_Audit> hash_file_info_audit { get; set; }
        public virtual ICollection<Hash_File_Info> hash_file_info { get; set; }
        public virtual ICollection<Hash_Collect_Record> hash_collect_record { get; set; }
        public virtual ICollection<Hash_File_Confirm_Statistics> hash_file_confirm_statistics { get; set; }
    }
}
