//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role : BaseModel
    {
        public Sys_Role()
        {
            this.Sys_Role_Right = new HashSet<Sys_Role_Right>();
            this.Sys_User_Role = new HashSet<Sys_User_Role>();
        }
    
    	[EntityPrimKey]
        public string Role_ID { get; set; }
        public string Role_Name { get; set; }
        public string Role_Code { get; set; }
        public string Role_Description { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
    
        public virtual ICollection<Sys_Role_Right> Sys_Role_Right { get; set; }
        public virtual ICollection<Sys_User_Role> Sys_User_Role { get; set; }
    }
}
