//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Department : BaseModel
    {
        public Sys_Department()
        {
            this.Sys_User = new HashSet<Sys_User>();
            this.hash_collect_set_statistics = new HashSet<Hash_Collect_Set_Statistics>();
            this.hash_file_info_upload_statistics = new HashSet<Hash_File_Info_Upload_Statistics>();
            this.hash_property_update_statistics = new HashSet<Hash_Property_Update_Statistics>();
            this.hash_collect_statistics = new HashSet<Hash_Collect_Statistics>();
            this.hash_collect_set = new HashSet<Hash_Collect_Set>();
            this.hash_file_confirm_statistics = new HashSet<Hash_File_Confirm_Statistics>();
        }
    
    	[EntityPrimKey]
        public string Department_ID { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Integer_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Industry { get; set; }
        public string Paths { get; set; }
        public string Department_Code { get; set; }
        public string Character_Code { get; set; }
        public string Contactor { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Remark { get; set; }
        public string Creator_ID { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Updater_ID { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    
        public virtual Sys_Area Sys_Area { get; set; }
        public virtual ICollection<Sys_User> Sys_User { get; set; }
        public virtual ICollection<Hash_Collect_Set_Statistics> hash_collect_set_statistics { get; set; }
        public virtual ICollection<Hash_File_Info_Upload_Statistics> hash_file_info_upload_statistics { get; set; }
        public virtual ICollection<Hash_Property_Update_Statistics> hash_property_update_statistics { get; set; }
        public virtual ICollection<Hash_Collect_Statistics> hash_collect_statistics { get; set; }
        public virtual ICollection<Hash_Collect_Set> hash_collect_set { get; set; }
        public virtual ICollection<Hash_File_Confirm_Statistics> hash_file_confirm_statistics { get; set; }
    }
}
