//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role_Right : BaseModel
    {
    	[EntityPrimKey]
        public string Role_Right_ID { get; set; }
        public string Buttons { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public string Creator_ID { get; set; }
        public string Remark { get; set; }
    
        public virtual Sys_Menu Sys_Menu { get; set; }
        public virtual Sys_Role Sys_Role { get; set; }
    }
}
