//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Fault : BaseModel
    {
    	[EntityPrimKey]
        public string Fault_ID { get; set; }
        public string Fault_Problem { get; set; }
        public string Fault_Content { get; set; }
        public string Telephone { get; set; }
        public string Fault_UserID { get; set; }
        public int Fault_Status { get; set; }
        public System.DateTime Create_Time { get; set; }
        public System.DateTime Update_Time { get; set; }
        public string Handler_UserID { get; set; }
        public Nullable<System.DateTime> Handler_Time { get; set; }
        public string Handler_Content { get; set; }
    }
}
