//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.companies = new HashSet<company>();
        }
    
    
    
    
    [EntityPrimKey("city")]
        public int Id { get; set; }
    
    
    
        public string province { get; set; }
    
    
    
        public string city_name { get; set; }
    
    
    
        public string type { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
    }
}
