//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.project_case1 = new HashSet<project_case>();
            this.users = new HashSet<user>();
        }
    
    
    
    
    [EntityPrimKey("company")]
        public int Id { get; set; }
    
    
    
        public string name { get; set; }
    
    
    
        public Nullable<int> introduce_page_id { get; set; }
    
    
    
        public Nullable<int> type_id { get; set; }
    
    
    
        public string address { get; set; }
    
    
    
        public string contact_name { get; set; }
    
    
    
        public Nullable<int> user_id { get; set; }
    
    
    
        public string site_url { get; set; }
    
    
    
        public string qq_number { get; set; }
    
    
    
        public string phone { get; set; }
    
    
    
        public string mobile { get; set; }
    
    
    
        public Nullable<int> city_id { get; set; }
    
    
    
        public string email { get; set; }
    
    
    
        public string company_image_path { get; set; }
    
    
    
        public string logo_path { get; set; }
    
    
    
        public Nullable<System.DateTime> create_time { get; set; }
    
    
    
        public Nullable<System.DateTime> update_time { get; set; }
    
    
    
        public string company_phone { get; set; }
    
        public virtual city city { get; set; }
        public virtual sys_dictionary sys_dictionary { get; set; }
        public virtual user user { get; set; }
        public virtual project_case project_case { get; set; }
        public virtual ICollection<project_case> project_case1 { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
