//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
    
    
    
    [EntityPrimKey("product")]
        public long id { get; set; }
    
    
    
        public string product_id { get; set; }
    
    
    
        public string product_name { get; set; }
    
    
    
        public string main_image { get; set; }
    
    
    
        public string detail_link_address { get; set; }
    
    
    
        public string first_level_category { get; set; }
    
    
    
        public string taoke_link { get; set; }
    
    
    
        public string price { get; set; }
    
    
    
        public string sales_amount { get; set; }
    
    
    
        public string percent { get; set; }
    
    
    
        public string salary { get; set; }
    
    
    
        public string wangwang { get; set; }
    
    
    
        public string saler_id { get; set; }
    
    
    
        public string shop_name { get; set; }
    
    
    
        public string platform_name { get; set; }
    
    
    
        public string coupon_id { get; set; }
    
    
    
        public string coupon_amount { get; set; }
    
    
    
        public string coupon_remaining { get; set; }
    
    
    
        public string coupon_money { get; set; }
    
    
    
        public Nullable<System.DateTime> coupon_start { get; set; }
    
    
    
        public Nullable<System.DateTime> coupon_end { get; set; }
    
    
    
        public string coupon_link { get; set; }
    
    
    
        public string coupon_taoke_link { get; set; }
    }
}
