//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_case
    {
        public project_case()
        {
            this.companies = new HashSet<company>();
        }
    
    
    
    
    [EntityPrimKey("project_case")]
        public int Id { get; set; }
    
    
    
        public string title { get; set; }
    
    
    
        public string descript { get; set; }
    
    
    
        public Nullable<int> type_id { get; set; }
    
    
    
        public string content { get; set; }
    
    
    
        public Nullable<int> company_id { get; set; }
    
    
    
        public Nullable<int> user_id { get; set; }
    
    
    
        public string main_image_path { get; set; }
    
    
    
        public Nullable<int> is_company_intro { get; set; }
    
    
    
        public Nullable<int> is_publish { get; set; }
    
    
    
        public Nullable<int> view_count { get; set; }
    
    
    
        public Nullable<System.DateTime> publish_time { get; set; }
    
    
    
        public Nullable<System.DateTime> create_time { get; set; }
    
    
    
        public Nullable<System.DateTime> update_time { get; set; }
    
    
    
        public string project_contact_phone { get; set; }
    
    
    
        public string project_address { get; set; }
    
    
    
        public string project_action_company { get; set; }
    
    
    
        public string project_design_company { get; set; }
    
    
    
        public string project_type { get; set; }
    
    
    
        public string project_name { get; set; }
    
    
    
        public string project_area { get; set; }
    
    
    
        public string product_metal { get; set; }
    
    
    
        public string product_ruler { get; set; }
    
    
    
        public string product_cence { get; set; }
    
    
    
        public string product_price { get; set; }
    
    
    
        public string product_address { get; set; }
    
    
    
        public Nullable<int> is_product { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
        public virtual company company { get; set; }
        public virtual sys_dictionary sys_dictionary { get; set; }
        public virtual user user { get; set; }
    }
}
