//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_dictionary
    {
        public sys_dictionary()
        {
            this.companies = new HashSet<company>();
            this.project_case = new HashSet<project_case>();
        }
    
    
    
    
    [EntityPrimKey("sys_dictionary")]
        public int id { get; set; }
    
    
    
        public string name { get; set; }
    
    
    
        public string value { get; set; }
    
    
    
        public string group { get; set; }
    
    
    
        public Nullable<System.DateTime> create_time { get; set; }
    
    
    
        public Nullable<System.DateTime> update_time { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<project_case> project_case { get; set; }
    }
}
